### ISSUE TITLE
Restrict NPC weapon cone

### ISSUE THREAD

**Issue by FJonske** [better-modernized-combat/bmod-client#93] opened 2024-05-07 17:08 UTC
Right now, they can fire sideways 90 degrees and through the roof. On Elites, this can essentially lead to the enemy perma-blasting you despite having clearly lost the turn battle. This behavior was in the old version of the mod, but less noticeable, I think. I believe we have all the tools to fix this, but would want @Beaglerush to give an opinion on that. 

Maybe 60 to 75 degrees would feel more reasonable?

Also, what are the weapon cones tied to? Hardpoints on ships or the guns? If guns, I suggest lowering the cone angle across the board, and anyone who we'd want to pop off a couple absurd shots through the roof, like aces, they'd get ships that turn better due to lower mass or something, and aggressive turning styles.

**Comment by Beaglerush** [comment] 2024-05-07 22:35
Just want to post that I'm aware of this and will start tweaking and playing with this. I like the overal feel of the mod's balance right now, so I'll be taking it slow but evaluating what it feels like to tweak this allowance down further.

Something to note about this is it isn't a purely NPC issue - this is just the allowance of the guns currently. DATA\constants.ini has the line MUZZLE_CONE_ANGLE which currently = 40. Iirc this means guns are allowed to fire 40 degrees off their barrel's bore, which is also swivelling naturally according to what the hardpoint of the ship allows in terms of traverse angles. If you go into game right now and use turret mode you'll see you can shoot almost straight up and down, just like the NPCs can.

Of course the big difference is that NPCs can shoot and move independently and aren't restricted to a camera in the way a normal human is, so this is rarely used by players but constantly by the AI. We can tune this individually for the AI if we like; we only need to set individual MUZZLE_CONE_ANGLE overrides for each gun specifically if we please. Note that this allowance is essential to some degree for allowing the AI to be effective though, as by default, their guns could only shoot where their barrel could physically draw a direct line to, which meant that in vanilla most enemies couldn't shoot all their guns at you at once most of the time because even their own ships were blocking their ability to aim at you with their full arsenal at any given moment.

I'd encourage you to try tweaking MUZZLE_CONE_ANGLE in constants.ini and then seeing for yourself - it's actually quick and easy to do and the results should be immediately apparent in any fight you undertake, unless the NPCs are using guns that have their own muzzle cone overrides. As said, I'll be playing with this cautiously from here on, especially with the elites. Also consider though it's actually not all guns hitting you all the time - for instance you can see for yourself if you go into turret mode right now that only two blasters can aim straight up, the cheek ones I think.

**Comment by Beaglerush** [comment] 2024-05-10 18:51
Closing this as it's not a bug and is firmly on my radar now in terms of ongoing balance.

**Closed by Beaglerush** 2024-05-10 18:51 UTC
Labels: bug
