### ISSUE TITLE
Select a helmet/spacesuit combo for a new default MP player character model to replace Trent with

### ISSUE THREAD

**Issue by Beaglerush** [better-modernized-combat/bmod-client#77] opened 2024-04-11 03:33 UTC

**Comment by FJonske** [comment] 2024-04-16 11:43
Strong vote for the helmet that's on the logo and game icon. It's *the* FL helmet, as far as I'm concerned. Even if it is a Liberty-specific one, we *are* in Liberty.

Now, if a player can modify this, that'd be sick. But yeah, out of scope, probably.

**Comment by IrateRedKite** [comment] 2024-05-21 16:21
Closing as a duplicate of https://github.com/better-modernized-combat/bmod-client/issues/116

**Closed by IrateRedKite** 2024-05-21 16:21 UTC
Labels: enhancement
