### ISSUE TITLE
AI crosshair placement

### ISSUE THREAD

**Issue by FJonske** [better-modernized-combat/bmod-client#35] opened 2024-01-29 13:02 UTC
We've discussed this before, and I think we need to figure out where the following observation is coming from, and if its real, how to mitigate it:

AI pilots appear to fire all weapons as one weapon group, and this seems to place their crosshair in a location that misses all weapons if two types of weapons with vastly different muzzle velocities appear in the loadout, leading their fire too much for one group and too little for the other. This is for example noticeable for Navy Guardians using two PPCs and a number of blasters, or Xenos Elites using M-Lasers. 

@Lazrius said this seems wrong, and I am inclined to agree it sounds stupid, but some experimentation has led me to believe it is the case, although some of that experimentation may have been in SP. In any case, does this happen, and if so, can we trick the AI into what is essentially weapon group usage?

I consider this a blocker for NPC loadout balancing, because finding a fix here means we should probably rebalance NPC weaponry, as we're essentially buffing NPCs by fixing this, and I'd rather do this sooner than later.

**Comment by IrateRedKite** [comment] 2024-01-29 20:43
I think step one here is confirming that NPCs _definitely_ behave in this way, as currently it's a bit ambiguous. If no-one beats me to it, I'd suggest setting up some local tests in MP and scientifically establishing that this is definitely what's going on before we put a ton of effort into remediating it.

**Comment by Beaglerush** [comment] 2024-01-29 22:16
Yes, I agree - we have to guarantee this is happening without a doubt before we think about how to fix it.

**Comment by IrateRedKite** [comment] 2024-01-29 22:29
Won't have the time or energy to sit down and test this for a few days, but I've set up a test encounter on the branch dev/ai-science with commit f1acc02fab905e3d6cc72bf86adbda007c534cb7. 

If anyone beats me to it, you can edit the `NPCShipArch` `bm_placeholder_all_grp_d1-19` or the loadout `bm_li_hf_li_n_grp_test` in Bm01 for this. We should think of some objective ways to test this, in both SP and MP. There's a very good chance the behaviours differ between the two which could be is why this feels

**Comment by FJonske** [comment] 2024-01-29 22:31
Will get on this on Friday or Saturday at the latest, maybe tomorrow. Give me experiments and I'll do them.

**Comment by Beaglerush** [comment] 2024-01-29 23:56
The way I would test this is use ridiculously high numbers at first - 10,000 m/s vs 1000 m/s - and compare it in the exact same situation but with a fully equal weapon group. Do a bunch of repeats of the situation to make sure it's not one-off flukes and ensure that there's no other differences in the experiment. Then, if there's demonstrably a difference between such a massive change in weapon group speeds, bring the numbers down until the difference isn't able to be observed anymore - 5000 m/s vs 1000 m/s, 2500 vs 1000, 2000, 1500, and so on.
It's possible that even if the issue is apparent at massive levels, it's insignificant or has different outcomes entirely at lower differences, and us knowing all of that will be useful for properly diagnosing this and also for any way we want to use this to intentionally balance enemy accuracy in the future.

**Comment by IrateRedKite** [comment] 2024-01-30 08:28
I did have a particular thought on this issue generally, that's that weapons tagged with `auto_turret = true` are handled in a different accuracy group when defining stuff in a pilots pop `[GunBlock]`. It's possible these are crosshaired differently, but would require testing to be sure.

**Comment by FJonske** [comment] 2024-01-30 09:06
> The way I would test this is use ridiculously high numbers at first - 10,000 m/s vs 1000 m/s - and compare it in the exact same situation but with a fully equal weapon group. Do a bunch of repeats of the situation to make sure it's not one-off flukes and ensure that there's no other differences in the experiment. Then, if there's demonstrably a difference between such a massive change in weapon group speeds, bring the numbers down until the difference isn't able to be observed anymore - 5000 m/s vs 1000 m/s, 2500 vs 1000, 2000, 1500, and so on. It's possible that even if the issue is apparent at massive levels, it's insignificant or has different outcomes entirely at lower differences, and us knowing all of that will be useful for properly diagnosing this and also for any way we want to use this to intentionally balance enemy accuracy in the future.

Isn't the difference we have ~30k/s for Lasers vs ~1.8k/s for the original Scorpion rn?

**Comment by IrateRedKite** [comment] 2024-01-30 09:45
> Isn't the difference we have ~30k/s for Lasers vs ~1.8k/s for the original Scorpion rn?

I think this is the case, although we may wish to unify Laser Speeds as small right now have a 10k velocity (partially due to how projectile lifetimes work). For the purposes of this test it's probably worth adjusting weapon values so they are more extreme, as we're just trying to find out if this behavior works as it appears right now

**Comment by IrateRedKite** [comment] 2024-02-10 22:40
@Beaglerush @FJonske I did a limited set of testing with stationary NPCs, and the laser definitely throws off their accuracy. However, giving the laser the `auto_turret = true` key, seems to fix this! it's not perfect, but it lets us give NPCs two weapon groups for high velocity weapons. If you want to see for yourselves, I've updated the dev/ai-testing branch, you can fight stationary Defenders in the Bm01_01_base system

This test was done in MP on a local server, not SP. Results may be different there.

**Comment by FJonske** [comment] 2024-02-11 01:06
Making a note here to set auto_turret = True for all NPC AUX weapons on principle. This should work nicely.

That said, this will probably increase the lethality of NPCs quite a bit, which we should keep in mind for future balancing.

**Comment by FJonske** [comment] 2024-02-11 01:20
Fix is in, leaving this open until after testing, then closing.

**Comment by IrateRedKite** [comment] 2024-02-29 22:34
After a bit of time with this one, fairly confident it's working. Closing the issue as resolved.

**Closed by IrateRedKite** 2024-02-29 22:34 UTC
Labels: bug, blocker
